# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from mcp_test_framework.test_code.response import ToolResponse


class DiscoverAndMapParams(BaseModel):
    """Params for the `discover_and_map` tool.

    Generated from inputSchema. Pydantic validates required / type /
    default rules at construction time before the wire call.
    """
    model_config = ConfigDict(extra="forbid")

    hostname: str = Field(..., description='Hostname or IP address')
    key_path: str | None = Field(default=None, description='Path to SSH private key')
    password: str | None = Field(default=None, description='SSH password (not needed for mcp_admin after setup)')
    port: int = Field(default=22, description='SSH port (default: 22)')
    username: str = Field(default='mcp_admin', description="SSH username. Defaults to 'mcp_admin' if omitted. Omit if credentials were stored with `credentials add` — they are auto-injected.")


class DiscoverAndMapResponse(ToolResponse):
    """Typed response for the `discover_and_map` tool.

    Inherits .raw / .data / .text / .is_error from ToolResponse.
    outputSchema was undeclared at codegen time; .data falls
    back to JSON-parse / text-dict via the locked fallback chain.
    """
    pass
