# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from mcp_test_framework.test_code.response import ToolResponse


class GetProxmoxNodeStatusParams(BaseModel):
    """Params for the `get_proxmox_node_status` tool.

    Generated from inputSchema. Pydantic validates required / type /
    default rules at construction time before the wire call.
    """
    model_config = ConfigDict(extra="forbid")

    node: str = Field(..., description="Node name (e.g., 'pve', 'proxmox')")
    host: str | None = Field(default=None, description='Proxmox host (optional, uses PROXMOX_HOST env var)')


class GetProxmoxNodeStatusResponse(ToolResponse):
    """Typed response for the `get_proxmox_node_status` tool.

    Inherits .raw / .data / .text / .is_error from ToolResponse.
    outputSchema was undeclared at codegen time; .data falls
    back to JSON-parse / text-dict via the locked fallback chain.
    """
    pass
