# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

import typing

from pydantic import BaseModel, ConfigDict, Field

from mcp_test_framework.test_code.response import ToolResponse


class ListProxmoxResourcesParams(BaseModel):
    """Params for the `list_proxmox_resources` tool.

    Generated from inputSchema. Pydantic validates required / type /
    default rules at construction time before the wire call.
    """
    model_config = ConfigDict(extra="forbid")

    host: str | None = Field(default=None, description='Proxmox host (optional, uses PROXMOX_HOST env var if not provided)')
    # codegen: degraded -- enum not in v1.3 coverage
    resource_type: typing.Any = Field(default=None, description='Filter by resource type')


class ListProxmoxResourcesResponse(ToolResponse):
    """Typed response for the `list_proxmox_resources` tool.

    Inherits .raw / .data / .text / .is_error from ToolResponse.
    outputSchema was undeclared at codegen time; .data falls
    back to JSON-parse / text-dict via the locked fallback chain.
    """
    pass
