# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from mcp_test_framework.test_code.response import ToolResponse


class RemoveServerPreviewParams(BaseModel):
    """Params for the `remove_server_preview` tool.

    Generated from inputSchema. Pydantic validates required / type /
    default rules at construction time before the wire call.
    """
    model_config = ConfigDict(extra="forbid")

    credential_id: int | None = Field(default=None, description='ID of the credential to remove (optional if hostname provided)')
    hostname: str | None = Field(default=None, description='Hostname to look up (optional if credential_id provided)')


class RemoveServerPreviewResponse(ToolResponse):
    """Typed response for the `remove_server_preview` tool.

    Inherits .raw / .data / .text / .is_error from ToolResponse.
    outputSchema was undeclared at codegen time; .data falls
    back to JSON-parse / text-dict via the locked fallback chain.
    """
    pass
