# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from mcp_test_framework.test_code.response import ToolResponse


class SetupMcpAdminParams(BaseModel):
    """Params for the `setup_mcp_admin` tool.

    Generated from inputSchema. Pydantic validates required / type /
    default rules at construction time before the wire call.
    """
    model_config = ConfigDict(extra="forbid")

    hostname: str = Field(..., description='Hostname or IP address of the target system')
    force_update_key: bool = Field(default=True, description='Force update SSH key even if mcp_admin already has keys (default: true)')
    password: str | None = Field(default=None, description='Password for the admin user. Omit if credentials were stored with `credentials add` — they are auto-injected.')
    port: int = Field(default=22, description='SSH port (default: 22)')
    timeout: float = Field(default=90, description='Timeout in seconds for the SSH operation. Setup can take 30-60s on slow hosts (default: 90)')
    username: str | None = Field(default=None, description='Admin username to connect with (must have sudo access). Omit if credentials were stored with `credentials add` — they are auto-injected.')


class SetupMcpAdminResponse(ToolResponse):
    """Typed response for the `setup_mcp_admin` tool.

    Inherits .raw / .data / .text / .is_error from ToolResponse.
    outputSchema was undeclared at codegen time; .data falls
    back to JSON-parse / text-dict via the locked fallback chain.
    """
    pass
