# AUTOGENERATED by mcp-test-framework gen-test-classes -- DO NOT HAND-EDIT.
# Source: homelab_mcp (serverInfo.name="homelab-mcp", version="1.4.0")
# Regenerated: 2026-05-29T05:15:09+00:00
# Extend by subclassing in tests/test_code/, not by editing this file.
from __future__ import annotations

import pytest

from mcp_test_framework.test_code import mcp_session, tool  # noqa: F401

from .update_device_config import UpdateDeviceConfigParams  # noqa: F401

pytest.skip(
    "no examples; populate tools.update_device_config.examples: in config.yaml to enable this smoke",
    allow_module_level=True,
)
